### ISSUE TITLE
Changelog for rewrite?

### ISSUE THREAD

**Issue by kennethormandy** [fusepilot/create-cep-extension#5]
Hey, I’m hoping to make more contributions to this project, but looks like everything is changing. Would you be able to share the reason behind the rewrite, or could we chat sometime about your future plans for this project? It looks like CRA is used directly now rather than this being more of a fork, is that correct?

In the meantime, I’ve tagged [my fork v1.0.0](https://github.com/kennethormandy/create-cep-extension) so I can continue to make changes I need as necessary, but I’d rather contribute directly to this project if possible. Some things I have that I’d like to open PRs for:

- Moving the `bundle.js` and main CSS file into the root of the build directory, maintains compatibility with CRA and fixes the static media URL paths (this might already be fixed if you’ve made things even more CRA-like)
- Command line UI for debugging URLs

Thanks!

**Comment by fusepilot** [comment]
Hey,

The first attempt at this was going through and sprinkling in CEP stuff as I became familiar with the internal structure of CRA. In the process I ended up removing a bunch stuff to simplify since CRA is fairly complex. Things like the command line generator, ejecting functionality, etc... So while that worked, it ended up being a pretty significant departure from CRA and wasn't really a fork. The rewrite tries to keep the CEP stuff as a separate layer on top of CRA while keeping most of its functionality untouched. Including the command line. Plus, this will hopefully make merging downstream CRA updates easier.

The first PR idea should already be fixed since its more CRA like. Let's discuss the Command line UI in a new PR, since I'm not sure what the idea is.

Let me know if you have any questions about getting up to speed to develop with the new ( CRA ) structure.

Thanks!
